import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServerClient } from "@/lib/supabaseServerClient";
import type { Workflow } from "@/types";

// Helper to execute Aloha actions
async function executeAlohaAction(action: string, context: any) {
  switch (action) {
    case "aloha.reorganize":
      return {
        success: true,
        message: "Aloha has reorganized your calendar and priorities",
        data: { reorganized: true },
      };
    case "aloha.scheduleFollowup":
      return {
        success: true,
        message: "Aloha has scheduled a follow-up",
        data: { scheduled: true, followUpDate: new Date().toISOString() },
      };
    default:
      return { success: false, message: `Unknown Aloha action: ${action}` };
  }
}

// Helper to execute Sync actions
async function executeSyncAction(action: string, context: any) {
  switch (action) {
    case "sync.summarize":
      return {
        success: true,
        message: "Sync has generated a summary",
        data: { summary: "Summary of recent emails and tasks generated by Sync" },
      };
    case "sync.createTask":
      return {
        success: true,
        message: "Sync has created a new task",
        data: { taskId: `task-${Date.now()}`, created: true },
      };
    default:
      return { success: false, message: `Unknown Sync action: ${action}` };
  }
}

// Helper to execute Studio actions
async function executeStudioAction(action: string, context: any) {
  switch (action) {
    case "studio.logMetric":
      return {
        success: true,
        message: "Studio has logged a new metric",
        data: { metricId: `metric-${Date.now()}`, logged: true },
      };
    case "studio.updateMetric":
      return {
        success: true,
        message: "Studio has updated metrics",
        data: { updated: true },
      };
    default:
      return { success: false, message: `Unknown Studio action: ${action}` };
  }
}

// Helper to execute Insight actions
async function executeInsightAction(action: string, context: any) {
  switch (action) {
    case "insight.combineOutputs":
      return {
        success: true,
        message: "Insight has combined outputs from all agents",
        data: { combined: true, summary: "Unified summary from all agents" },
      };
    case "insight.sendSummary":
      return {
        success: true,
        message: "Insight has sent a summary",
        data: { sent: true, recipient: context.recipient || "user" },
      };
    default:
      return { success: false, message: `Unknown Insight action: ${action}` };
  }
}

// Check if workflow condition matches
function checkCondition(condition: Workflow["condition"], context: any): boolean {
  if (!condition) return true;

  const { field, operator, value } = condition;
  const fieldValue = context[field];

  switch (operator) {
    case "contains":
      return fieldValue?.toString().toLowerCase().includes(value?.toString().toLowerCase() || "");
    case "equals":
      return fieldValue === value;
    case "greaterThan":
      return Number(fieldValue) > Number(value);
    case "lessThan":
      return Number(fieldValue) < Number(value);
    case "exists":
      return fieldValue !== undefined && fieldValue !== null;
    default:
      return false;
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { workflowId, trigger, context = {} } = body;

    if (!workflowId && !trigger) {
      return NextResponse.json(
        { error: "Either workflowId or trigger is required" },
        { status: 400 }
      );
    }

    const supabase = getSupabaseServerClient();
    let workflow: Workflow | null = null;

    // If workflowId provided, fetch the workflow
    if (workflowId) {
      const { data, error } = await supabase
        .from("workflows")
        .select("*")
        .eq("id", workflowId)
        .eq("enabled", true)
        .single();

      if (error && error.code !== "PGRST116") {
        throw error;
      }

      workflow = data;
    }

    // If trigger provided, find matching workflows
    if (trigger && !workflow) {
      const { data, error } = await supabase
        .from("workflows")
        .select("*")
        .eq("trigger", trigger)
        .eq("enabled", true);

      if (error && error.code !== "PGRST116") {
        throw error;
      }

      // Find workflow that matches condition
      if (data && data.length > 0) {
        workflow = data.find((w) => checkCondition(w.condition, context)) || data[0];
      }
    }

    if (!workflow) {
      return NextResponse.json(
        { error: "No matching workflow found" },
        { status: 404 }
      );
    }

    // Check condition if workflow has one
    if (workflow.condition && !checkCondition(workflow.condition, context)) {
      return NextResponse.json({
        ok: true,
        message: "Workflow condition not met",
        executed: false,
      });
    }

    // Execute all actions
    const results = [];
    for (const action of workflow.actions) {
      let result;
      
      if (action.startsWith("aloha.")) {
        result = await executeAlohaAction(action, context);
      } else if (action.startsWith("sync.")) {
        result = await executeSyncAction(action, context);
      } else if (action.startsWith("studio.")) {
        result = await executeStudioAction(action, context);
      } else if (action.startsWith("insight.")) {
        result = await executeInsightAction(action, context);
      } else {
        result = { success: false, message: `Unknown action: ${action}` };
      }

      results.push({
        action,
        ...result,
      });
    }

    return NextResponse.json({
      ok: true,
      workflowId: workflow.id,
      workflowName: workflow.name,
      executed: true,
      results,
    });
  } catch (error: any) {
    console.error("Error running workflow:", error);
    return NextResponse.json(
      { ok: false, error: error.message || "Failed to run workflow" },
      { status: 500 }
    );
  }
}





